// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoucherApp.Infrastructure.Data;

#nullable disable

namespace VoucherApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VoucherApp.Core.Entities.RewardTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketType")
                        .HasColumnType("int");

                    b.Property<int>("BatchQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("RewardTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasketType = 1,
                            BatchQuantity = 8,
                            Category = 0,
                            Name = "Zniżka 10 PLN",
                            Value = 10m
                        },
                        new
                        {
                            Id = 2,
                            BasketType = 1,
                            BatchQuantity = 8,
                            Category = 1,
                            Name = "Zniżka 15%",
                            Value = 15m
                        });
                });

            modelBuilder.Entity("VoucherApp.Core.Entities.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRedeemed")
                        .HasColumnType("bit");

                    b.Property<Guid>("QrCodeContent")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RewardTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("QrCodeContent")
                        .IsUnique();

                    b.HasIndex("RewardTemplateId");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("VoucherApp.Core.Entities.Voucher", b =>
                {
                    b.HasOne("VoucherApp.Core.Entities.RewardTemplate", "RewardTemplate")
                        .WithMany()
                        .HasForeignKey("RewardTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewardTemplate");
                });
#pragma warning restore 612, 618
        }
    }
}
